/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include "STM32F103x6.h"
#include "gpio.h"

void clock_init(){
	//Enable clock for GPIO PortA
	RCC_GPIOA_CLK_ENABLE();

	//Enable clock for GPIO PortB
	RCC_GPIOB_CLK_ENABLE();
}

void GPIO_init(){

	GPIO_PinConfig_t PinConfig;

	//PA1 (Input Floating "HI-Z")
	//Floating Input + Output Push/Pull (0100)
	PinConfig.GPIO_PinNumber = GPIO_PIN_1;
	PinConfig.GPIO_MODE = GPIO_MODE_INPUT_FLOAT;
	MCAL_GPIO_init(GPIOA, &PinConfig);

	//PB1 (Output Push/Pull Mode)
	//Push/Pull Output + Max Speed 10MHz (0001)
	PinConfig.GPIO_PinNumber = GPIO_PIN_1;
	PinConfig.GPIO_MODE = GPIO_MODE_OUTPUT_PP;
	PinConfig.GPIO_OUTPUT_SPEED = GPIO_OUTPUT_SPEED_10M;
	MCAL_GPIO_init(GPIOB, &PinConfig);

	//PA13 (Input Floating "HI-Z")
	//Floating Input + Output Push/Pull (0100)
	PinConfig.GPIO_PinNumber = GPIO_PIN_13;
	PinConfig.GPIO_MODE = GPIO_MODE_INPUT_FLOAT;
	MCAL_GPIO_init(GPIOA, &PinConfig);

	//PB13 (Output Push/Pull Mode)
	//Push/Pull Output + Max Speed 10MHz (0001)
	PinConfig.GPIO_PinNumber = GPIO_PIN_13;
	PinConfig.GPIO_MODE = GPIO_MODE_OUTPUT_PP;
	PinConfig.GPIO_OUTPUT_SPEED = GPIO_OUTPUT_SPEED_10M;
	MCAL_GPIO_init(GPIOB, &PinConfig);
}

void delay(int n){
	uint32_t i, j;
	for(i = 0; i < n; i++)
		for(j = 0; j < 255; j++);
}

int main(void)
{
	clock_init();
	GPIO_init();

	while(1){
		if(MCAL_GPIO_ReadPin(GPIOA, GPIO_PIN_1) == 0){ //PUR
			//Switch is Pressed
			MCAL_GPIO_TogglePin(GPIOB, GPIO_PIN_1);
			while(MCAL_GPIO_ReadPin(GPIOA, GPIO_PIN_1) == 0); //Single Pressed
		}

		if(MCAL_GPIO_ReadPin(GPIOA, GPIO_PIN_13) == 1){ //PDR
			//Switch is Pressed
			MCAL_GPIO_TogglePin(GPIOB, GPIO_PIN_13);
		}
		delay(1);
	}
}
